### ISSUE TITLE
可以上传到nuget

### ISSUE THREAD

**Issue by aidenwlf** [yureng/nanoFramework.Modbus#1]
方便使用

**Comment by yureng** [comment]
nanoFramework 已许可将 nanoFramework.Modbus 加入到 [nanoFramework.IoT.Device](https://github.com/nanoframework/nanoFramework.IoT.Device) 库，和官方库一起 nuget 包 。

但是全部代码语法需要通过 StyleCop 书写规范检查。
因最近没有时间，所以尚未开始这项工作。
