### ISSUE TITLE
Please add customized seiralport support

### ISSUE THREAD

**Issue by JohnMasen** [yureng/nanoFramework.Modbus#2]
Current modbus client constructor accepts SerialPortName only
``` C#
public ModbusClient(
            string portName,
            int baudRate = 9600,
            Parity parity = Parity.None,
            int dataBits = 8,
            StopBits stopBits = StopBits.One
            ) : base(portName, baudRate, parity, dataBits, stopBits)
        {
        }
```

can you please add a new constructor to allow user pass exiting serialPort like the code below? The reason is code in Port.CS ```_serialPort.Mode = SerialMode.RS485``` does not work on my device, it would be good I could just pass my serialport class directly to the ModbusClient.
```C#
        public ModbusClient(SerialPort port):base(port)
        {
            
        }

```

this may require change the Port.CS like this 
``` C#
  public abstract class Port : IDisposable
    {
        private SerialPort _serialPort;

        public Port(
            string portName,
            int baudRate,
            Parity parity,
            int dataBits,
            StopBits stopBits,
            int ReceivedBytesThreshold = 1
            )
        {
            _serialPort = new SerialPort(portName, baudRate, parity, dataBits, stopBits);
            _serialPort.Mode = SerialMode.RS485;
            _serialPort.Handshake = Handshake.RequestToSend;
            _serialPort.ReceivedBytesThreshold = ReceivedBytesThreshold;
        }

        public Port(SerialPort port)
        {
            _serialPort = port;
        }
}
```

**Comment by yureng** [comment]
Already added.

**Comment by yureng** [comment]
> Current modbus client constructor accepts SerialPortName only
> 
> ```cs
> public ModbusClient(
>             string portName,
>             int baudRate = 9600,
>             Parity parity = Parity.None,
>             int dataBits = 8,
>             StopBits stopBits = StopBits.One
>             ) : base(portName, baudRate, parity, dataBits, stopBits)
>         {
>         }
> ```
> 
> can you please add a new constructor to allow user pass exiting serialPort like the code below? The reason is code in Port.CS `_serialPort.Mode = SerialMode.RS485` does not work on my device, it would be good I could just pass my serialport class directly to the ModbusClient.
> 
> ```cs
>         public ModbusClient(SerialPort port):base(port)
>         {
>             
>         }
> ```
> 
> this may require change the Port.CS like this
> 
> ```cs
>   public abstract class Port : IDisposable
>     {
>         private SerialPort _serialPort;
> 
>         public Port(
>             string portName,
>             int baudRate,
>             Parity parity,
>             int dataBits,
>             StopBits stopBits,
>             int ReceivedBytesThreshold = 1
>             )
>         {
>             _serialPort = new SerialPort(portName, baudRate, parity, dataBits, stopBits);
>             _serialPort.Mode = SerialMode.RS485;
>             _serialPort.Handshake = Handshake.RequestToSend;
>             _serialPort.ReceivedBytesThreshold = ReceivedBytesThreshold;
>         }
> 
>         public Port(SerialPort port)
>         {
>             _serialPort = port;
>         }
> }
> ```

Already added.

**Comment by yureng** [comment]
Close the issues
